import pyautogui as py
import time as t
t.sleep(0.5)
py.press('winleft')
t.sleep(0.5)
py.write('chrome')
t.sleep(0.5)
py.press('enter')
t.sleep(1.5)
t.sleep(0.5)
py.write('www.gmail.com', interval=0.05)
t.sleep(0.5)
py.press('enter')
t.sleep(2.5)
py.moveTo(65, 214)
t.sleep(2.5)
py.click()
t.sleep(9.0)
py.write('--')
py.press('enter')
t.sleep(9.0)
py.press('tab')
py.write('--')
t.sleep(2.0)
py.press('tab')
t.sleep(2.0)
py.write('--')
py.press('enter')
py.write('--')
py.moveTo(1022, 825)
t.sleep(1.0)
py.click()
py.moveTo(336, 286)
t.sleep(1.0)
py.click()
py.moveTo(1228, 761)
t.sleep(1.0)
py.click()
t.sleep(8.0)
py.hotkey('ctrl', 'enter')
